# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authentication.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authentication_password(object):
    def setupUi(self, Authentication_password):
        Authentication_password.setObjectName("Authentication_password")
        Authentication_password.resize(310, 100)
        Authentication_password.setMinimumSize(QtCore.QSize(310, 100))
        Authentication_password.setMaximumSize(QtCore.QSize(310, 100))
        self.verticalLayout = QtWidgets.QVBoxLayout(Authentication_password)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_authentification_password = QtWidgets.QFrame(Authentication_password)
        self.frame_authentification_password.setMaximumSize(QtCore.QSize(310, 100))
        self.frame_authentification_password.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_authentification_password.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_authentification_password.setObjectName("frame_authentification_password")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_authentification_password)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_authentification_password)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_authentification_password)
        self.lineEdit_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_password.setText("")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_2.addWidget(self.lineEdit_password)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_authentification_password)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.frame_authentification_password)

        self.retranslateUi(Authentication_password)
        self.buttonBox.accepted.connect(Authentication_password.accept) # type: ignore
        self.buttonBox.rejected.connect(Authentication_password.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Authentication_password)

    def retranslateUi(self, Authentication_password):
        _translate = QtCore.QCoreApplication.translate
        Authentication_password.setWindowTitle(_translate("Authentication_password", "Authentication"))
        self.label.setText(_translate("Authentication_password", "Write Your Password ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Authentication_password = QtWidgets.QDialog()
    ui = Ui_Authentication_password()
    ui.setupUi(Authentication_password)
    Authentication_password.show()
    sys.exit(app.exec_())
