Image_1:
   OriIns:
        Height: 2612
        Icy: 98.0
        Icx: 1529.7475
        Width: 4000
        Fx: 134.0
        Fy: 134.25475306831868
   Ins:
        Height: 2612
        Icy: 98.0
        Icx: 1529.7475
        Width: 4000
        Fx: 134.0
        Fy: 134.25475306831868
   src:
        point1_x: 1428
        point1_y: 142
        point2_x: 1631
        point2_y: 152
        point3_x: 1256
        point3_y: 268
        point4_x: 1799
        point4_y: 296
   dst:
        point1_x: 920
        point1_y: 456
        point2_x: 1639
        point2_y: 461
        point3_x: 921
        point3_y: 803
        point4_x: 1625
        point4_y: 783
        Height: 1010
        Width: 2592

Image_2:
   OriIns:
        Height: 2612
        Icy: 98.0
        Icx: 1529.7475
        Width: 4000
        Fx: 134.0
        Fy: 134.25475306831868
   Ins:
        Height: 2337
        Icy: 83.0
        Icx: 5000
        Width: 6000
        Fx: 151.0
        Fy: 150.31321321702728
   src:
        point1_x: 4807
        point1_y: 190
        point2_x: 5126
        point2_y: 162
        point3_x: 4326
        point3_y: 511
        point4_x: 5329
        point4_y: 316
   dst:
        point1_x: 1724
        point1_y: 426
        point2_x: 2604
        point2_y: 423
        point3_x: 1703
        point3_y: 787
        point4_x: 2607
        point4_y: 787
        Height: 960
        Width: 3657
Image_3:
   OriIns:
        Height: 2612
        Icy: 98.0
        Icx: 1529.7475
        Width: 4000
        Fx: 134.0
        Fy: 134.25475306831868
   Ins:
        Height: 2337
        Icy: 83.0
        Icx: 3002
        Width: 4000
        Fx: 151.0
        Fy: 150.31321321702728
   src:
        point1_x: 2848
        point1_y: 170
        point2_x: 3156
        point2_y: 177
        point3_x: 2516
        point3_y: 399
        point4_x: 3425
        point4_y: 398
   dst:
        point1_x: 1064
        point1_y: 405
        point2_x: 1990
        point2_y: 408
        point3_x: 1064
        point3_y: 787
        point4_x: 1990
        point4_y: 787
        Height: 973
        Width: 3657
Image_4:
   OriIns:
        Height: 2612
        Icy: 98.0
        Icx: 1529.7475
        Width: 4000
        Fx: 134.0
        Fy: 134.25475306831868
   Ins:
        Height: 2337
        Icy: 83.0
        Icx: 3002
        Width: 4000
        Fx: 151.0
        Fy: 150.31321321702728
   src:
        point1_x: 2916
        point1_y: 127
        point2_x: 3132
        point2_y: 123
        point3_x: 2794
        point3_y: 258
        point4_x: 3318
        point4_y: 274
   dst:
        point1_x: 934
        point1_y: 437
        point2_x: 1666
        point2_y: 442
        point3_x: 926
        point3_y: 787
        point4_x: 1666
        point4_y: 787
        Height: 1010
        Width: 2592
camera_placement: corner
camera_used: 4