Image_1:
  Ins:
    Fx: 134.0
    Fy: 134.25
    Height: 2612
    Icx: 1529.75
    Icy: 98.0
    Width: 4000
  dst:
    Height: 1010
    Width: 2592
    point1_x: 920
    point1_y: 465
    point2_x: 1639
    point2_y: 465
    point3_x: 921
    point3_y: 783
    point4_x: 1625
    point4_y: 783
  maps_x: data_config/maps/map_x_1.npy
  maps_y: data_config/maps/map_y_1.npy
  src:
    point1_x: 1448
    point1_y: 134
    point2_x: 1613
    point2_y: 142
    point3_x: 1204
    point3_y: 314
    point4_x: 1844
    point4_y: 331
Image_2:
  Ins:
    Fx: 151.0
    Fy: 150.31
    Height: 2337
    Icx: 5000.0
    Icy: 83.0
    Width: 6000
  dst:
    Height: 960
    Width: 3657
    point1_x: 1724
    point1_y: 426
    point2_x: 2604
    point2_y: 423
    point3_x: 1703
    point3_y: 787
    point4_x: 2607
    point4_y: 787
  maps_x: data_config/maps/map_x_2.npy
  maps_y: data_config/maps/map_y_2.npy
  src:
    point1_x: 4807
    point1_y: 190
    point2_x: 5126
    point2_y: 162
    point3_x: 4326
    point3_y: 511
    point4_x: 5329
    point4_y: 316
Image_3:
  Ins:
    Fx: 151.0
    Fy: 150.31
    Height: 2337
    Icx: 3002.0
    Icy: 83.0
    Width: 4000
  dst:
    Height: 973
    Width: 3657
    point1_x: 1064
    point1_y: 405
    point2_x: 1990
    point2_y: 408
    point3_x: 1064
    point3_y: 787
    point4_x: 1990
    point4_y: 787
  maps_x: data_config/maps/map_x_3.npy
  maps_y: data_config/maps/map_y_3.npy
  src:
    point1_x: 2848
    point1_y: 170
    point2_x: 3156
    point2_y: 177
    point3_x: 2516
    point3_y: 399
    point4_x: 3425
    point4_y: 398
Image_4:
  Ins:
    Fx: 151.0
    Fy: 150.31
    Height: 2337
    Icx: 3002.0
    Icy: 83.0
    Width: 4000
  dst:
    Height: 1010
    Width: 2592
    point1_x: 934
    point1_y: 437
    point2_x: 1666
    point2_y: 442
    point3_x: 926
    point3_y: 787
    point4_x: 1666
    point4_y: 787
  maps_x: data_config/maps/map_x_4.npy
  maps_y: data_config/maps/map_y_4.npy
  src:
    point1_x: 2916
    point1_y: 127
    point2_x: 3132
    point2_y: 123
    point3_x: 2794
    point3_y: 258
    point4_x: 3318
    point4_y: 274
camera_placement: center
camera_used: 4
